import type { Equipment, MaintenanceRequest, Team, Technician } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => {
  const img = PlaceHolderImages.find((p) => p.id === id);
  return {
    url: img?.imageUrl || 'https://picsum.photos/seed/placeholder/600/400',
    hint: img?.imageHint || 'placeholder',
  };
};

export const technicians: Technician[] = [
  { id: 'tech-1', name: 'Ravi Kumar', workload: 3 },
  { id: 'tech-2', name: 'Priya Sharma', workload: 5 },
  { id: 'tech-3', name: 'Anil Singh', workload: 2 },
  { id: 'tech-4', name: 'Sunita Patel', workload: 4 },
  { id: 'tech-5', name: 'Vijay Mehta', workload: 4 },
];

export const teams: Team[] = [
  { id: 'team-a', name: 'Maintenance', members: ['tech-1', 'tech-3'] },
  { id: 'team-b', name: 'Electrical', members: ['tech-2', 'tech-4'] },
  { id: 'team-c', name: 'HVAC', members: [] },
  { id: 'team-d', name: 'Production', members: [] },
  { id: 'team-e', name: 'Safety', members: [] },
];

export const equipment: Equipment[] = [
  {
    id: 'equip-001',
    name: 'Industrial Pump X-1000',
    serialNumber: 'SN-IPX1000-2023-01',
    location: 'Mumbai Plant, Sector A',
    department: 'Manufacturing',
    assignedEmployee: 'Rajesh Gupta',
    maintenanceTeamId: 'team-a',
    defaultTechnicianId: 'tech-1',
    isScrapped: false,
    maintenanceFrequency: 30,
    imageUrl: findImage('equipment-1').url,
    imageHint: findImage('equipment-1').hint,
  },
  {
    id: 'equip-002',
    name: 'Conveyor Belt Z-200',
    serialNumber: 'SN-CBZ200-2022-05',
    location: 'Delhi Plant, Packing Area',
    department: 'Logistics',
    assignedEmployee: 'Priya Mehta',
    maintenanceTeamId: 'team-a',
    defaultTechnicianId: 'tech-3',
    isScrapped: false,
    maintenanceFrequency: 90,
    imageUrl: findImage('equipment-2').url,
    imageHint: findImage('equipment-2').hint,
  },
  {
    id: 'equip-003',
    name: 'CNC Machine V-5',
    serialNumber: 'SN-CNCV5-2021-11',
    location: 'Mumbai Plant, Sector B',
    department: 'Manufacturing',
    assignedEmployee: 'Sanjay Reddy',
    maintenanceTeamId: 'team-b',
    defaultTechnicianId: 'tech-2',
    isScrapped: false,
    maintenanceFrequency: 60,
    imageUrl: findImage('equipment-3').url,
    imageHint: findImage('equipment-3').hint,
  },
  {
    id: 'equip-004',
    name: 'Forklift F-80',
    serialNumber: 'SN-FF80-2020-03',
    location: 'Delhi Warehouse',
    department: 'Logistics',
    assignedEmployee: 'Sunita Rao',
    maintenanceTeamId: 'team-a',
    defaultTechnicianId: 'tech-1',
    isScrapped: true,
    maintenanceFrequency: 120,
    imageUrl: findImage('equipment-4').url,
    imageHint: findImage('equipment-4').hint,
  },
];

export const requests: MaintenanceRequest[] = [
  {
    id: 'RQ-1042',
    subject: 'Fix Leaking Pump',
    equipmentId: 'equip-001',
    teamId: 'team-a',
    technicianId: 'tech-1',
    type: 'corrective',
    status: 'in_progress',
    priority: 'High',
    scheduledDate: new Date('2023-05-25'),
    duration: 0,
    rootCause: '',
    createdBy: 'Rajesh Gupta',
  },
  {
    id: 'RQ-1037',
    subject: 'Inspect HVAC System',
    equipmentId: 'equip-001',
    teamId: 'team-c',
    technicianId: 'tech-2',
    type: 'preventive',
    status: 'new',
    priority: 'Medium',
    scheduledDate: new Date('2023-05-23'),
    duration: 2,
    rootCause: '',
    createdBy: 'System',
  },
  {
    id: 'RQ-1028',
    subject: 'Replace Conveyor Belt',
    equipmentId: 'equip-002',
    teamId: 'team-a',
    technicianId: 'tech-3',
    type: 'corrective',
    status: 'repaired',
    priority: 'High',
    scheduledDate: new Date('2023-05-20'),
    duration: 4,
    rootCause: 'Routine Check',
    createdBy: 'Priya Mehta',
  },
  {
    id: 'RQ-1019',
    subject: 'Calibrate Pressure Gauge',
    equipmentId: 'equip-003',
    teamId: 'team-b',
    technicianId: 'tech-4',
    type: 'corrective',
    status: 'in_progress',
    priority: 'Low',
    scheduledDate: new Date('2023-05-19'),
    duration: 0,
    rootCause: '',
    createdBy: 'Sanjay Reddy',
  },
  {
    id: 'RQ-1005',
    subject: 'Test Emergency Lights',
    equipmentId: 'equip-004',
    teamId: 'team-e',
    technicianId: 'tech-5',
    type: 'preventive',
    status: 'new',
    priority: 'Medium',
    scheduledDate: new Date('2023-05-17'),
    duration: 40,
    rootCause: 'Major engine failure',
    createdBy: 'System',
  },
  {
    id: 'req-06',
    subject: 'Annual Inspection',
    equipmentId: 'equip-002',
    teamId: 'team-a',
    technicianId: 'tech-3',
    type: 'preventive',
    status: 'new',
    priority: 'Medium',
    scheduledDate: new Date(new Date().setDate(new Date().getDate() + 15)),
    duration: 0,
    rootCause: '',
    createdBy: 'System',
  },
   {
    id: 'req-07',
    subject: 'Hydraulic fluid leak',
    equipmentId: 'equip-001',
    teamId: 'team-a',
    technicianId: 'tech-1',
    type: 'corrective',
    status: 'repaired',
    priority: 'Medium',
    scheduledDate: new Date(new Date().setDate(new Date().getDate() - 5)),
    duration: 3,
    rootCause: 'Worn out seal',
    createdBy: 'Rajesh Gupta',
  },
  {
    id: 'req-08',
    subject: 'Monthly lubrication service',
    equipmentId: 'equip-003',
    teamId: 'team-b',
    technicianId: 'tech-2',
    type: 'preventive',
    status: 'in_progress',
    priority: 'Low',
    scheduledDate: new Date(),
    duration: 1,
    rootCause: '',
    createdBy: 'System',
  },
];
